apiVersion: v1
kind: Namespace
metadata:
  name: epsagon-monitoring
  labels:
    name: epsagon-monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: epsagon-monitoring
  namespace: epsagon-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: epsagon-prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - services/proxy
  - endpoints
  - pods
  - pods/proxy
  - pods/log
  - namespaces
  - configmaps
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: epsagon-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: epsagon-prometheus
subjects:
- kind: ServiceAccount
  name: epsagon-monitoring
  namespace: epsagon-monitoring
